### ISSUE TITLE
Awaiting mocha release with fixed timeout(0) regression

### ISSUE THREAD

**Issue by jasisk** [krakenjs/generator-kraken#120]
Related to #118 and visionmedia/mocha#1300.

Presently, timeout(0) in mocha doesn't act as documented, subsequently breaking out tests. To workaround the issue I pegged mocha to ~1.20 in 0d89749866d69942e1e1e648246bd96b2297372e.

Issue to be resolved in the next mocha release as demonstrated by visionmedia/mocha@4c0c47978accc76fa1e1e2b22ee158ff8198d019 and visionmedia/mocha@35da58bdd551ec0a0cdb3eacb884a83d141aca63.

**Comment by grawk** [comment]
resolved with https://github.com/krakenjs/generator-kraken/pull/208 (mocha had fixed the core issue a while ago but this PR modifies the `this.timeout` statements in the tests)
