### ISSUE TITLE
Generating the file structure seems to not be working as intended. 

### ISSUE THREAD

**Issue by jhorwit2** [krakenjs/generator-kraken#133]
I have tried this on my main dev machine and fresh images and still running into this. 

If I run yo kraken (even with sudo) it's not generating all the directories (for example I'm missing controllers). 

```
Directory after running yo kraken <name>

config
Gruntfile.js
index.js
locales
package.json
public
README.md
tasks
```

I'm stumped, any ideas? This is even happening on my dev machine after doing updating a day or so ago when before it worked fine. (this isn't my first kraken app)

**Comment by grawk** [comment]
My bug fix branch was subsumed by a subsequent refactor and then a fix on top of the new generator factoring for this issue. It's now published as `2.1.1`. I'm going to close this as it should resolve the issue raised here.
