### ISSUE TITLE
Generator does not exit automatically when running with node v 0.12

### ISSUE THREAD

**Issue by nigampatel** [krakenjs/generator-kraken#159]
I updated my node version to 0.12.0 and ran yo kraken to generate an app. App does get generated correctly but after all the node modules are installed, the process does not end.  It is forcing me to hit enter to go back to the prompt.  

Note: I had to update node-sass to version 2.0.1, in order to avoid install error.

**Comment by dncrews** [comment]
:+1:

**Comment by grawk** [comment]
This doesn't happen for me. It could be that some intermediate fixes/changes to the generator have resolved whatever issue you did see. If you don't mind, @nigampatel can you confirm whether you still see this issue with v2.1.2 of the generator?

**Comment by grawk** [comment]
Closing. Please reopen if you are seeing this issue with `v2.2.0` and currently latest `v0.12` patch.
