### ISSUE TITLE
"Respond to JSON requests" - What does this do?

### ISSUE THREAD

**Issue by tkambler** [krakenjs/generator-kraken#167]
When creating a new controller via the generator's `controller` subcommand, users are prompted as to whether the controller should respond to JSON requests. See below:

![json](https://dl.dropboxusercontent.com/u/832215/pro-javascript-images/yo-kraken-controller.png)

What is the purpose of this prompt? I have answered this question both ways, and can see no difference between the files that are created in each case.

**Comment by aredridel** [comment]
Which version of the generator are you using?

This shouldn't happen with 1.1.2 or 2.0.0, but I'd love to know what you end up with.

**Comment by aredridel** [comment]
It emits a more thorough route handler. It's a bit of legacy that I think should go away. But you should never be asked the question in version 2.0.0.
