### ISSUE TITLE
Change to the Docs

### ISSUE THREAD

**Issue by maxehnert** [krakenjs/generator-kraken#171]
I just installed this generator and created a new application. Before I could run `npm start` I needed to first run `npm install`. In most generators this is taken care of. Is this typical of this generator to still need to run `npm install` before anything can be done? Also, I already have Bower (1.4.1) installed globally but didn't see anything about needing to run `bower init` in the docs, only from looking through the issues did I find that I need to do that to create a `bower.json` file.

**Comment by aredridel** [comment]
I think there's a bug around that and I think I fixed it in my last refactor. there's some gnarly stuff in this generator and I'm trying to straighten it out. Stay tuned! I'll check on the new revision as I test it.

**Comment by aredridel** [comment]
This is fixed.
