### ISSUE TITLE
yo kraken:layout generates dust into incorrect directory

### ISSUE THREAD

**Issue by grawk** [krakenjs/generator-kraken#177]
`yo kraken:layout` generates the layout dust file into the main `templates` directory instead of `templates/layouts`

**Comment by grawk** [comment]
Nevermind. Of course you can always add path info on the command line :/

**Comment by aredridel** [comment]
Ah, that makes sense. I'm torn on that. I like suggesting order, but I see no easy way to do that without imposing order.

**Comment by grawk** [comment]
The generator is complex enough already (in terms of maintenance). So I don't mind leaving this choice with the consumer at all.

**Comment by aredridel** [comment]
Indeed. I reduced the interdependency, but not the complexity of each part when I rewrote it.
