### ISSUE TITLE
Dust helper via Makara 2 does it work ?

### ISSUE THREAD

**Issue by ygrenzinger** [krakenjs/generator-kraken#183]
Hello,

I'm trying to make a transition in my one year app to the updated libs of the Kraken generator.

I am using Dust helper like {@eq ...}A{:else}B{/eq} but nothing happens. I have tried with a fresh generated app but nothing happen too.

Does I have a configuration missing ? Or do I have to go back to old engine-munger / adaro libs ?

Thanks,

**Comment by aredridel** [comment]
How are you loading the helper?

**Comment by ygrenzinger** [comment]
Maybe not. Do you talk about: 
"dust": {
        "helpers": ["dust-makara-helpers"]
    }
in config file ?
If it's in server.js or index.js I don't think so.

If it can help, my whole code is here: https://github.com/ygrenzinger/absainte/tree/kraken-update

**Comment by ygrenzinger** [comment]
Ok I think I have understood.

Do I have to put:
"dust": {
"helpers": ["dust-makara-helpers", "dust-helpers"]
}
?

**Comment by aredridel** [comment]
Yep! That's what you'd do to load those helpers. They're optional, and so not included by default. Makara doesn't make any decisions for you it doesn't have to.
