### ISSUE TITLE
How to migrate spec.js in Makara 2 ?

### ISSUE THREAD

**Issue by ygrenzinger** [krakenjs/generator-kraken#184]
Hello,

I continue with another question for the migration to Makara 2 :)

Without Makara 2, there is a spec.js file which seems automatically loaded by Kraken. With makara 2, it doesn't seem to be loaded anymore. What is the correct new way ?

In config.json there is a "specialization": {} but I don't know how to use it and it seems to be for something like A/B testing. 

@aredridel I think I will have many question do I keep to ask them here or should I talk to you by mail ?

Bonus question: is it sure that Makara 2 is the future "standard" way with KrakenJS ?

**Comment by ygrenzinger** [comment]
Sorry to fast on that. I have retrieved the link between Kraken and spec.js :)

**Comment by aredridel** [comment]
I'd like to see makara 2 broadly adopted -- I'll continue to be involved in the project at least. It solves problems with very large applications and lots of templates.

Yes, specialization is good for a/b testing -- feel free to leave it out -- but it lets you specify rules to replace one template with another at runtime, without modifying the calling code. It's a good simple way to run experiments without the code for it leaking everywhere.

**Comment by ygrenzinger** [comment]
Great !

I have solved my regression with spec.js. 

But few problems remain:
- construx doesn't seems to work (changing dust template doesn't have any effect before app restart)
- Setting the locale at runtime doesn't have any effect (for example with res.locals.context = {locality: locale}; )

If you have some tips :)

**Comment by aredridel** [comment]
- Do you have caching turned on in the view engine? That will break construx.

- Set the locale at `req.locale` and `res.locals.locale`. I am killing the `context` stuff, and the name `locality` is complex too. We have a backward compat shim within paypal, I can extract that if you need, but porting should be simple. `express-bcp47` package should give an example of setting it properly. (and itself will work for you if your locale is based on the accept header)

**Comment by ygrenzinger** [comment]
thanks you a lot for your help ! Everything seems fine :)

**Comment by aredridel** [comment]
Excellent! Love having any feedback on the new design.
