### ISSUE TITLE
missing modules from generated package.json

### ISSUE THREAD

**Issue by vmaudgalya** [krakenjs/generator-kraken#187]
On selecting the default options after issuing the 'yo kraken' command, I find that the generated package.json file is consistently missing modules and does not run "out of the box". It requires an npm install of each of the following modules to run:

dust-makara-helpers
construx-dustjs
makara
construx-less

I am using node version 0.12.0, npm version 2.5.1, running on OS X

**Comment by jasisk** [comment]
Hi @vmaudgalya,

Unfortunately, I'm unable to reproduce. Could you post a log?

``` sh
$ npm ls -g --depth=0
/usr/local/lib
└── (empty)

$ npm i -g yo bower generator-kraken
# ... SNIP ...

$ yo kraken

     ,'""`.
hh  / _  _ \
    |(@)(@)|   Release the Kraken!
    )  __  (
   /,'))((`.\
  (( ((  )) ))
   `\ `)(' /'

Tell me a bit about your application:

? Name: app
? Description: app
? Author: app
? Template library? Dust (via Makara 2)
? Include i18n support? Yes
? Front end package manager ? Bower
? CSS preprocessor library? LESS
? JavaScript library? RequireJS
   create package.json
   create public/templates/layouts/master.dust
   create models/index.js
   create public/templates/index.dust
   create locales/US/en/layouts/master.properties
   create locales/US/en/index.properties
   create Gruntfile.js
   create README.md
   create config/config.json
   create config/development.json
   create index.js
   create public/favicon.ico
   create public/js/app.js
   create server.js
   create tasks/clean.js
   create tasks/copyto.js
   create tasks/jshint.js
   create tasks/mochacli.js
   create .editorconfig
   create .jshintignore
   create .jshintrc
   create .nodemonignore
   create .npmignore
   create public/templates/errors/404.dust
   create public/templates/errors/500.dust
   create public/templates/errors/503.dust
   create tasks/dustjs.js
   create locales/US/en/errors/404.properties
   create locales/US/en/errors/500.properties
   create locales/US/en/errors/503.properties
   create .bowerrc
   create public/css/app.less
   create tasks/less.js
   create tasks/requirejs.js
   create controllers/index.js
   create test/index.js
# ... SNIP ...

$ cd app; npm ls --depth=0
app@0.1.0 /Users/jsisk/tmp/app
├── construx@1.0.0
├── construx-copier@1.0.0
├── construx-dustjs@1.1.0
├── construx-less@1.0.0
├── dust-makara-helpers@4.1.2
├── express@4.13.3
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── grunt-config-dir@0.3.2
├── grunt-contrib-clean@0.6.0
├── grunt-contrib-jshint@0.10.0
├── grunt-contrib-less@1.0.1
├── grunt-contrib-requirejs@0.4.4
├── grunt-copy-to@0.0.10
├── grunt-dustjs@1.2.1
├── grunt-makara-amdify@1.0.1
├── grunt-mocha-cli@1.14.0
├── kraken-js@1.0.6
├── makara@2.0.3
├── mocha@1.21.5
├── requirejs@2.1.20
└── supertest@0.9.2

$ npm t

> app@0.1.0 test /Users/jsisk/tmp/app
> grunt test

Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "mochacli:src" (mochacli) task


  index
::ffff:127.0.0.1 - - [22/Sep/2015:23:50:44 +0000] "GET / HTTP/1.1" 200 268 "-" "-"
    ✓ should say "hello" (182ms)


  1 passing (630ms)


Done, without errors.
```

**Comment by vmaudgalya** [comment]
Sure thing.

LM-SJN-21000651:sample vmaudgalya$ yo kraken

     ,'""`. 
hh  / _  _ \
    |(@)(@)|   Release the Kraken!
    )  __  (
   /,'))((`.\ 
  (( ((  )) ))
   `\ `)(' /'

Tell me a bit about your application:

? Name: test
? Description: test
? Author: test
? Template library? Dust (via Makara 2)
? Include i18n support? Yes
? Front end package manager ? Bower
? CSS preprocessor library? LESS
? JavaScript library? RequireJS
   create package.json
   create public/templates/layouts/master.dust
   create models/index.js
   create public/templates/index.dust
   create locales/US/en/layouts/master.properties
   create locales/US/en/index.properties
   create config/config.json
   create config/development.json
   create Gruntfile.js
   create index.js
   create public/favicon.ico
   create public/js/app.js
   create README.md
   create server.js
   create tasks/clean.js
   create tasks/copyto.js
   create tasks/jshint.js
   create tasks/mochacli.js
   create .editorconfig
   create .jshintignore
   create .jshintrc
   create .nodemonignore
   create .npmignore
   create public/templates/errors/404.dust
   create public/templates/errors/500.dust
   create public/templates/errors/503.dust
   create tasks/dustjs.js
   create locales/US/en/errors/404.properties
   create locales/US/en/errors/500.properties
   create locales/US/en/errors/503.properties
   create .bowerrc
   create public/css/app.less
   create tasks/less.js
   create tasks/requirejs.js
   create controllers/index.js
   create test/index.js
npm WARN package.json test@0.1.0 No repository field.
construx-copier@1.0.0 node_modules/construx-copier

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── content-type@1.0.1
├── etag@1.7.0
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.7)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

construx@1.0.0 node_modules/construx
├── debuglog@1.0.1
├── n-deep-merge@0.0.1
├── async@0.2.10
├── mkdirp@0.3.5
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.2)
└── rimraf@2.4.3 (glob@5.0.14)

supertest@0.9.2 node_modules/supertest
├── methods@0.1.0
└── superagent@0.17.0 (methods@0.0.1, cookiejar@1.3.0, extend@1.2.1, qs@0.6.5, debug@0.7.4, emitter-component@1.0.0, reduce-component@1.0.1, mime@1.2.5, formidable@1.0.14)

kraken-js@1.0.6 node_modules/kraken-js
├── debuglog@0.0.4
├── core-util-is@1.0.1
├── cookie-parser@1.4.0 (cookie-signature@1.0.6, cookie@0.2.2)
├── shush@0.0.1 (strip-json-comments@0.1.3)
├── meddleware@1.0.0
├── serve-favicon@2.3.0 (fresh@0.3.0, etag@1.7.0, ms@0.7.1, parseurl@1.3.0)
├── lusca@1.3.0
├── formidable@1.0.17
├── shortstop@1.0.1 (async@0.2.10)
├── endgame@0.0.3
├── morgan@1.6.1 (basic-auth@1.0.3, on-headers@1.0.0, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── confit@1.2.0 (debuglog@1.0.1, shortstop-handlers@0.1.0, minimist@0.0.10, async@0.7.0)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── express-session@1.11.3 (cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, on-headers@1.0.0, parseurl@1.3.0, depd@1.0.1, uid-safe@2.0.0, crc@3.3.0, debug@2.2.0)
├── compression@1.5.2 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, debug@2.2.0, compressible@2.0.5, accepts@1.2.13)
├── shortstop-resolve@1.0.1 (resolve@1.1.6)
├── caller@0.0.1 (tape@2.3.3)
├── shortstop-handlers@1.0.0 (glob@3.2.11)
├── express-enrouten@1.2.1 (debuglog@1.0.1, path-to-regexp@1.2.1, caller@1.0.0)
├── body-parser@1.14.0 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.3, debug@2.2.0, qs@5.1.0, type-is@1.6.8, iconv-lite@0.4.11)
└── bluebird@1.2.4

mocha@1.21.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
LM-SJN-21000651:sample vmaudgalya$ cd test/
LM-SJN-21000651:test vmaudgalya$ npm start

> test@0.1.0 start /Users/vmaudgalya/projects/sample/test
> node server.js

Server listening on http://localhost:8000
Possibly unhandled Error: Cannot find module 'makara'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/vmaudgalya/projects/sample/test/node_modules/kraken-js/lib/views.js:34:18
    at Array.forEach (native)
    at views (/Users/vmaudgalya/projects/sample/test/node_modules/kraken-js/lib/views.js:30:26)
    at tryCatch1 (/Users/vmaudgalya/projects/sample/test/node_modules/kraken-js/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/vmaudgalya/projects/sample/test/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/vmaudgalya/projects/sample/test/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:711:18)

**Comment by jasisk** [comment]
hmmm.. could you run the following:
```
npm ls -g --depth=0
```

**Comment by vmaudgalya** [comment]
Script started on Tue Sep 22 17:55:35 2015
[?1034hsh-3.2$ ~ /[K[K[K. ~/.nvm/nvm.sh 
sh-3.2$ nv[K[Knvm use[K[K[Kinstall 012[K[K.0[K12.0

                                                                           1.3%
##                                                                         2.9%
####                                                                       6.2%
#######                                                                   10.3%
##########                                                                14.8%
##############                                                            19.5%
#################                                                         24.0%
####################                                                      28.9%
########################                                                  34.0%
############################                                              39.5%
################################                                          44.6%
###################################                                       49.9%
#######################################                                   55.2%
###########################################                               60.7%
###############################################                           66.3%
###################################################                       72.0%
#######################################################                   76.7%
###########################################################               82.3%
###############################################################           87.8%
###################################################################       93.4%
#######################################################################   99.1%
######################################################################## 100.0%
Now using node v0.12.0 (npm v2.5.1)
sh-3.2$ nvm[K[K[Knpm install -g yo generator-kraken
-[0G\[0G|[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G
 

> spawn-sync@1.0.13 postinstall /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G-[0G\[0G|[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G
 

> spawn-sync@1.0.13 postinstall /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G/Users/vmaudgalya/.nvm/versions/node/v0.12.0/bin/yo -> /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/yo/lib/cli.js

> yo@1.4.8 postinstall /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/yo
> yodoctor


[4m[34mYeoman Doctor[39m[24m
Running sanity checks on your system

[32m✔[39m Global configuration file is valid
[32m✔[39m NODE_PATH matches the npm root
[32m✔[39m Node.js version
[31m✖[39m No .bowerrc file in home directory

We found a [36mundefined[39m file in your home directory. This can cause
issues by overriding expected default config. Prefer setting up one `.bowerrc` per
project.

To delete the file, run: [35mrm ~/.bowerrc[39m

[32m✔[39m No .yo-rc.json file in home directory
[31m✖[39m npm version

[31mYour npm version is outdated.[39m

Upgrade to the latest version by running:
[35mnpm install -g npm[39m

[31m
Found potential issues on your machine :([39m
generator-kraken@2.1.0 /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/generator-kraken
├── debuglog@1.0.1
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── underscore.string@3.2.2
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.1, semver-diff@2.0.0, latest-version@1.0.1, configstore@0.3.2)
└── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, path-exists@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, async@1.4.2, xdg-basedir@2.0.0, user-home@2.0.0, dargs@4.0.1, text-table@0.2.0, mime@1.3.4, istextorbinary@1.0.2, debug@2.2.0, nopt@3.0.4, run-async@0.1.0, pretty-bytes@2.0.1, shelljs@0.5.3, cli-table@0.3.1, through2@2.0.0, dateformat@1.0.11, glob@5.0.14, diff@2.1.1, findup-sync@0.2.1, github-username@2.0.0, cross-spawn@2.0.0, mem-fs-editor@2.0.4, download@4.2.0, class-extend@0.1.1, yeoman-environment@1.2.7, html-wiring@1.2.0, gruntfile-editor@1.0.0, sinon@1.17.0, lodash@3.10.1, inquirer@0.8.5)

yo@1.4.8 /Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.4.0
├── async@1.4.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── opn@3.0.2 (object-assign@3.0.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── root-check@1.0.0 (sudo-block@1.2.0, downgrade-root@1.1.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, indent-string@1.2.2, minimist@1.2.0)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, strip-ansi@2.0.1, word-wrap@1.1.0, pad-component@0.0.1, taketalk@1.0.0, minimist@1.2.0, string-width@1.0.1)
├── configstore@1.2.1 (os-tmpdir@1.0.1, object-assign@3.0.0, graceful-fs@4.1.2, xdg-basedir@2.0.0, osenv@0.1.3, uuid@2.0.1, write-file-atomic@1.1.3, mkdirp@0.5.1)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── got@4.2.0 (lowercase-keys@1.0.0, is-stream@1.0.1, timed-out@2.0.0, is-redirect@1.0.0, prepend-http@1.0.3, is-plain-obj@1.0.0, unzip-response@1.0.0, object-assign@3.0.0, node-status-codes@1.0.0, create-error-class@2.0.1, pinkie-promise@1.0.0, parse-json@2.2.0, read-all-stream@3.0.1, duplexify@3.4.2)
├── npm-keyword@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── package-json@1.2.0 (registry-url@3.0.3, got@3.3.1)
├── fullname@1.1.1 (npmconf@2.1.2)
├── cross-spawn@0.4.1 (lru-cache@2.7.0, spawn-sync@1.0.13)
├── inquirer@0.9.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, run-async@0.1.0, rx-lite@2.5.2)
├── yeoman-doctor@1.4.0 (object-values@1.0.0, log-symbols@1.0.2, user-home@1.1.1, each-async@1.1.1, bin-version-check@2.1.0, semver@4.3.6, twig@0.8.2)
├── lodash@3.10.1
├── insight@0.6.0 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-name@1.0.3, tough-cookie@1.2.0, request@2.63.0, inquirer@0.8.5)
└── yeoman-environment@1.2.7 (log-symbols@1.0.2, escape-string-regexp@1.0.3, diff@1.4.0, untildify@2.1.0, text-table@0.2.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0, inquirer@0.8.5)
[2Ksh-3.2$ yo kraken

[34m     ,'""`. [39m
[34mhh  / _  _ \[39m
[34m    |(@)(@)|  [39m [37m[1mRelease the Kraken![22m[39m
[34m    )  __  ([39m
[34m   /,'))((`.\ [39m
[34m  (( ((  )) ))[39m
[34m   `\ `)(' /'[39m

Tell me a bit about your application:

[32m?[39m [1mName:[22m a[204D[2K[32m?[39m [1mName:[22m a[28D[9Cp[204D[2K[32m?[39m [1mName:[22m ap[29D[10Cp[204D[2K[32m?[39m [1mName:[22m app[30D[11C

[204D[2K[1A[204D[2K[32m?[39m [1mName:[22m [36mapp[39m
[?25h[32m?[39m [1mDescription:[22m a[204D[2K[32m?[39m [1mDescription:[22m a[35D[16Cp[204D[2K[32m?[39m [1mDescription:[22m ap[36D[17Cp[204D[2K[32m?[39m [1mDescription:[22m app[37D[18C

[204D[2K[1A[204D[2K[32m?[39m [1mDescription:[22m [36mapp[39m
[32m?[39m [1mAuthor:[22m a[204D[2K[32m?[39m [1mAuthor:[22m a[30D[11Cp[204D[2K[32m?[39m [1mAuthor:[22m ap[31D[12Cp[204D[2K[32m?[39m [1mAuthor:[22m app[32D[13C

[204D[2K[1A[204D[2K[32m?[39m [1mAuthor:[22m [36mapp[39m
[32m?[39m [1mTemplate library?[22m [2m(Use arrow keys)[22m
[36m❯ Dust (via Makara 2)[39m 
  Dust 
  None [?25l[204D[2K[1A[204D[2K[1A[204D[2K[1A[204D[2K[32m?[39m [1mTemplate library?[22m [36mDust (via Makara 2)[39m
[?25h[32m?[39m [1mInclude i18n support?[22m [2m(Use arrow keys)[22m
[36m❯ Yes[39m 
  No [?25l[204D[2K[1A[204D[2K[1A[204D[2K[32m?[39m [1mInclude i18n support?[22m [36mYes[39m
[?25h[32m?[39m [1mFront end package manager ?[22m [2m(Use arrow keys)[22m
[36m❯ Bower[39m 
  No [?25l[204D[2K[1A[204D[2K[1A[204D[2K[32m?[39m [1mFront end package manager ?[22m [36mBower[39m
[?25h[32m?[39m [1mCSS preprocessor library?[22m [2m(Use arrow keys)[22m
[36m❯ LESS[39m 
  SASS 
  Stylus 
  None [?25l[204D[2K[1A[204D[2K[1A[204D[2K[1A[204D[2K[1A[204D[2K[32m?[39m [1mCSS preprocessor library?[22m [36mLESS[39m
[?25h[32m?[39m [1mJavaScript library?[22m [2m(Use arrow keys)[22m
[36m❯ RequireJS[39m 
  Browserify 
  None [?25l[204D[2K[1A[204D[2K[1A[204D[2K[1A[204D[2K[32m?[39m [1mJavaScript library?[22m [36mRequireJS[39m
[?25h[?25h[32m   create[39m package.json
[32m   create[39m public/templates/layouts/master.dust
[32m   create[39m models/index.js
[32m   create[39m public/templates/index.dust
[32m   create[39m locales/US/en/layouts/master.properties
[32m   create[39m locales/US/en/index.properties
[32m   create[39m config/config.json
[32m   create[39m config/development.json
[32m   create[39m Gruntfile.js
[32m   create[39m index.js
[32m   create[39m public/favicon.ico
[32m   create[39m public/js/app.js
[32m   create[39m README.md
[32m   create[39m server.js
[32m   create[39m tasks/clean.js
[32m   create[39m tasks/copyto.js
[32m   create[39m tasks/jshint.js
[32m   create[39m tasks/mochacli.js
[32m   create[39m .editorconfig
[32m   create[39m .jshintignore
[32m   create[39m .jshintrc
[32m   create[39m .nodemonignore
[32m   create[39m .npmignore
[32m   create[39m public/templates/errors/404.dust
[32m   create[39m public/templates/errors/500.dust
[32m   create[39m public/templates/errors/503.dust
[32m   create[39m tasks/dustjs.js
[32m   create[39m locales/US/en/errors/404.properties
[32m   create[39m locales/US/en/errors/500.properties
[32m   create[39m locales/US/en/errors/503.properties
[32m   create[39m .bowerrc
[32m   create[39m public/css/app.less
[32m   create[39m tasks/less.js
[32m   create[39m tasks/requirejs.js
[32m   create[39m controllers/index.js
[32m   create[39m test/index.js
[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mpackage.json[0m app@0.1.0 No repository field.
[0m-[0G\[0G|[0G/[0G-[0G\[0G|[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0Gconstrux-copier@1.0.0 node_modules/construx-copier

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── methods@1.1.1
├── cookie-signature@1.0.6
├── fresh@0.3.0
├── range-parser@1.0.2
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
└── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.7)

construx@1.0.0 node_modules/construx
├── debuglog@1.0.1
├── n-deep-merge@0.0.1
├── async@0.2.10
├── mkdirp@0.3.5
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── concat-stream@1.5.0 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.2)
└── rimraf@2.4.3 (glob@5.0.14)

supertest@0.9.2 node_modules/supertest
├── methods@0.1.0
└── superagent@0.17.0 (methods@0.0.1, extend@1.2.1, cookiejar@1.3.0, qs@0.6.5, debug@0.7.4, emitter-component@1.0.0, reduce-component@1.0.1, mime@1.2.5, formidable@1.0.14)

kraken-js@1.0.6 node_modules/kraken-js
├── debuglog@0.0.4
├── core-util-is@1.0.1
├── cookie-parser@1.4.0 (cookie-signature@1.0.6, cookie@0.2.2)
├── meddleware@1.0.0
├── serve-favicon@2.3.0 (fresh@0.3.0, ms@0.7.1, etag@1.7.0, parseurl@1.3.0)
├── lusca@1.3.0
├── formidable@1.0.17
├── shush@0.0.1 (strip-json-comments@0.1.3)
├── shortstop@1.0.1 (async@0.2.10)
├── endgame@0.0.3
├── morgan@1.6.1 (basic-auth@1.0.3, on-headers@1.0.0, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── confit@1.2.0 (debuglog@1.0.1, shortstop-handlers@0.1.0, minimist@0.0.10, async@0.7.0)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── express-session@1.11.3 (cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, on-headers@1.0.0, parseurl@1.3.0, depd@1.0.1, crc@3.3.0, debug@2.2.0, uid-safe@2.0.0)
├── compression@1.5.2 (bytes@2.1.0, vary@1.0.1, on-headers@1.0.0, debug@2.2.0, compressible@2.0.5, accepts@1.2.13)
├── shortstop-resolve@1.0.1 (resolve@1.1.6)
├── shortstop-handlers@1.0.0 (glob@3.2.11)
├── caller@0.0.1 (tape@2.3.3)
├── express-enrouten@1.2.1 (debuglog@1.0.1, path-to-regexp@1.2.1, caller@1.0.0)
├── body-parser@1.14.0 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.3, debug@2.2.0, qs@5.1.0, type-is@1.6.8, iconv-lite@0.4.11)
└── bluebird@1.2.4

mocha@1.21.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
[2Ksh-3.2$ cd app/
sh-3.2$ npm start

> app@0.1.0 start /Users/vmaudgalya/projects/sample/app
> node server.js

Server listening on http://localhost:8000
Possibly unhandled Error: Cannot find module 'makara'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/vmaudgalya/projects/sample/app/node_modules/kraken-js/lib/views.js:34:18
    at Array.forEach (native)
    at views (/Users/vmaudgalya/projects/sample/app/node_modules/kraken-js/lib/views.js:30:26)
    at tryCatch1 (/Users/vmaudgalya/projects/sample/app/node_modules/kraken-js/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/vmaudgalya/projects/sample/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/vmaudgalya/projects/sample/app/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:711:18)
^C
sh-3.2$ npm ls -g --depth=0
/Users/vmaudgalya/.nvm/versions/node/v0.12.0/lib
├── generator-kraken@2.1.0
├── npm@2.5.1
└── yo@1.4.8

sh-3.2$ exit
exit

Script done on Tue Sep 22 17:58:03 2015

**Comment by jasisk** [comment]
Yeah, you're missing [bower](http://bower.io).

This will fix your problem:

```
npm i -g bower
```

**Comment by vmaudgalya** [comment]
@jasisk that fixed it

**Comment by jasisk** [comment]
Glad to hear it! :grinning:
