### ISSUE TITLE
move to eslint

### ISSUE THREAD

**Issue by xjamundx** [krakenjs/generator-kraken#195]
this should move to eslint (per the latest internal paypal usage)

**Comment by grawk** [comment]
#198 was opened and references this issue. However that PR adds a prompt option to choose between JSHint and ESLint. I would recommend we don't offer an option but add eslint by default. The author of that PR hasn't responded about this but someone can open up a new one in the meantime.

**Comment by aravindsrivats** [comment]
I pushed a new commit that sets eslint by default on Nov.24 to the PR but the travis build failed only for Node v.10

**Comment by grawk** [comment]
resolved as of `v2.2.2`
