### ISSUE TITLE
update krakenjs version

### ISSUE THREAD

**Issue by amitmtrn** [krakenjs/generator-kraken#206]
currently the generator work with kraken version 1.0.3 and there is already version 2.x.
I think it would be best to update the generator to support kraken 2.x.

**Comment by grawk** [comment]
Hi @amitmtrn, yes, good call. Will try and get to this soon.

**Comment by brakon** [comment]
waiting for this 👍

**Comment by grawk** [comment]
ok. srsly looking now :eyes:

**Comment by odorisioe** [comment]
+1 for this update
How I can install/update the v2?

**Comment by grawk** [comment]
There isn't really much to change at all. If you use the currently released generator to make an app, just modify your package.json file after the initial creation and run `npm update`. The only reason this PR is stalled is that all the unit tests are currently failing. Looking into that.

**Comment by grawk** [comment]
resolved with the publish of `generator-kraken@2.2.3`
